version: '2'

services:
    db:
        image: mysql:5.7
        volumes:
            - /var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=root

    php:
        build: .
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/var/www/html
        links:
            - db

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - "8080:80"
        environment:
            - PMA_HOST=db
            - PMA_USER=root
            - PMA_PASSWORD=root
        links:
            - db
